/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package observa;
import java.awt.event.KeyEvent;
import javax.swing.*;
import java.util.*;
import modelo.ModeloJframe1;
/**
 *
 * @author positivo
 */
public class pgmt extends javax.swing.JFrame {
    ModeloJframe1 model = new ModeloJframe1();
    double tudo;
    Object[] lista;
    /**
     * Creates new form pgmt
     */
    public pgmt() {
        initComponents();
    }
    
    public void exportarPreco(double total, Object[] poo) {
        tudo = total;
        lista = poo;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(249, 249, 249));
        jPanel1.setLayout(null);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(415, 127, 0, 0);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image3/tomoe.JPG"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(250, 140, 76, 100);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image3/tomoe2.JPG"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 123, 95);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image3/nnanami.JPG"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(350, 110, 110, 140);

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setText("Como deseja obter o produto?");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(130, 30, 320, 50);

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 0));
        jButton1.setText("Loja");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(40, 130, 80, 23);

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 3, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 153));
        jLabel8.setText("Clique aqui se deja pegar diretamente na loja");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(80, 100, 290, 17);

        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 0, 0));
        jButton2.setText("Domicílio");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(100, 180, 90, 23);

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 3, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 153));
        jLabel9.setText("E aqui, se deseja entrega a domicílio");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 220, 230, 15);

        jLabel11.setText("↳");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 130, 40, 20);

        jLabel12.setText("↲");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(200, 180, 40, 20);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 250));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

 Random cod = new Random(); 
 int cod1 = cod.nextInt(9999);
 JOptionPane.showMessageDialog(null,"O codigo do seu pedido é: "+cod1);
 Object[] options = {"Confirmar"};
int n = JOptionPane.showOptionDialog(null,
                "****Use esse codigo para ganhar um brinde****\n Válido apenas para pedidos retirados na loja!!",
                "☺☺☺☺☺☺☺☺",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE,
                null,
                options,
                options[0]);
 //JOptionPane.showMessageDialog(null,"Redirecionando para o pagamento... ");
pgmtloja loj = new pgmtloja();
loj.exportarPreco(tudo, lista, cod1);
loj.setVisible(true);
this.dispose();
//    telafim2 tela2  = new telafim2();
    //tela2.exportarPreco(tudo);
    //tela2.setVisible(true);
    //this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        
    adicional adc = new adicional();
    adc.exportarPreco(tudo, lista);
    adc.setVisible(true);
   this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER){
       
   
        Random cod = new Random(); 
 int cod1 = cod.nextInt(9999);
 JOptionPane.showMessageDialog(null,"O codigo do seu pedido é: "+cod1);
 Object[] options = {"Confirmar"};
int n = JOptionPane.showOptionDialog(null,
                "****Use esse codigo para ganhar um brinde****\n Válido apenas para pedidos retirados na loja!!!!",
                "☺☺☺☺☺☺☺☺",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE,
                null,
                options,
                options[0]);
 //JOptionPane.showMessageDialog(null,"Redirecionando para o pagamento... ");
    pgmtloja loj = new pgmtloja();
    loj.exportarPreco(tudo, lista, cod1);
    loj.setVisible(true);

    //telafim2 tela2  = new telafim2();
   // tela2.setVisible(true);
   this.dispose();
   }
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
         adicional adc = new adicional();
    adc.exportarPreco(tudo, lista);
    adc.setVisible(true);
   this.dispose();
    }//GEN-LAST:event_jButton2KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pgmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pgmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pgmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pgmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pgmt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
