/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package observa;

import javax.swing.DefaultListModel;
import modelo.ModeloJframe1;
import java.util.ArrayList;
import java.util.List;
import java.util.*;

/**
 *
 * @author positivo
 */
public class telafim1 extends javax.swing.JFrame {

public void exportList(ModeloJframe1 model) {
    lblopa.setText(model.getLista());

}
    int tudodnvsapora;
    /**
     * Creates new form telafim1
     */
    public telafim1() {
        initComponents();
    }
    
    public telafim1(ModeloJframe1 model) {
        initComponents();
//        setListaFinal(model);
//        setList(model);
    }
    
    private ModeloJframe1 model;
    
public class ListBasedListModel<T> {

    private List<T> data;

    public ListBasedListModel(List<T> data) {
        this.data = data;
    }
}
    /*    public setListaFinal(ModeloJframe1 model) {
        this.model = model;
    }
    
    
    public setList(ModeloJframe1 model) {
        DefaultListModel itemslista = new DefaultListModel();
        itemsfinal.setModel(model.getListin());
    }
*/    
//    public void exportarPreco(double total) {
//       total = tudodnvsapora;
//    }
public void exportarTroco(int trooco, double total, Object[] listaa, String endrc, String numerocasa, String naoaguentomais) {
    endereco.setText(endrc);
    casanum.setText(numerocasa);
    referencia.setText(naoaguentomais);
    DefaultListModel listModel = new DefaultListModel();
    ArrayList<String> all = new ArrayList<>();
    all = new ArrayList (Arrays.asList(listaa));
    for (String percorrer : all) {
        listModel.addElement(percorrer);
    }
    itemsfinal.setModel(listModel);
/*     IMPORTANTE    
    
    ArrayList<String> all = new ArrayList<>();
    List list = Arrays.asList(listaa);
    all = (ArrayList) list;
    String[] str = new String [all.size()];
    
    for (String percorrer : str) {
        listModel.addElement(percorrer);
    }
    itemsfinal.setModel(listModel);
    
    
    
    */
//    lblopa.setText(listaa);
    Double newData = total;
    int frss = newData.intValue();
//    int frstd = (int)total;
//    tudodnvsapora = frstd;
    int tooootal = trooco - frss - 2;
    
    
    if (trooco > 0) {
    String troco = String.valueOf(tooootal);
    if (tooootal > 0) {
    lbltroco.setText("Seu troco: " + troco);    
    }
    }
    
    int toootal = frss + 2;
    String naotroco = String.valueOf(toootal);
    lblpagar.setText(naotroco);    
}

public void exportarPreco(int trooco, double tudomesmomano, Object[] risuto, String adress, String rfpoint, String number) {
    endereco.setText(adress);
    casanum.setText(number);
    referencia.setText(rfpoint);
    DefaultListModel listModel = new DefaultListModel();
    ArrayList<String> all = new ArrayList<>();
    all = new ArrayList (Arrays.asList(risuto));
    for (String percorrer : all) {
        listModel.addElement(percorrer);
    }
    itemsfinal.setModel(listModel);
//    lblopa.setText(listaa);
    Double newData = tudomesmomano;
    int frss = newData.intValue();
//    int frstd = (int)total;
//    tudodnvsapora = frstd;
    int tooootal = trooco - frss - 2;
    
    
    if (trooco > 0) {
    String troco = String.valueOf(tooootal);
    if (tooootal > 0) {
    lbltroco.setText("Seu troco: " + troco);    
    }
    }
    
    int toootal = frss + 2;
    String naotroco = String.valueOf(toootal);
    lblpagar.setText(naotroco);    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblpagar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        endereco = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbltroco = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemsfinal = new javax.swing.JList<>();
        lblopa = new javax.swing.JLabel();
        casanum = new javax.swing.JLabel();
        referencia = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(243, 149, 147));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblpagar.setFont(new java.awt.Font("MS Gothic", 2, 11)); // NOI18N
        lblpagar.setText("montante");
        jPanel1.add(lblpagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, 20));

        jLabel3.setFont(new java.awt.Font("MS Gothic", 3, 11)); // NOI18N
        jLabel3.setText("Total a pagar:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, 20));

        endereco.setFont(new java.awt.Font("MS Gothic", 2, 12)); // NOI18N
        endereco.setText("endrc");
        jPanel1.add(endereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 220, 30));

        jLabel1.setFont(new java.awt.Font("MS Gothic", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Agradecemos a preferencia");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image4/kokuri.JPG"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, 100));

        lbltroco.setFont(new java.awt.Font("MS Gothic", 3, 11)); // NOI18N
        jPanel1.add(lbltroco, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 128, 20));

        jLabel4.setFont(new java.awt.Font("MS Gothic", 3, 12)); // NOI18N
        jLabel4.setText("Local de entrega:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 460, 40));

        itemsfinal.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(itemsfinal);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 100, 80));

        lblopa.setBackground(new java.awt.Color(153, 204, 0));
        lblopa.setForeground(new java.awt.Color(243, 149, 147));
        jPanel1.add(lblopa, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 30, 20));

        casanum.setFont(new java.awt.Font("MS Gothic", 2, 11)); // NOI18N
        casanum.setText("numero");
        jPanel1.add(casanum, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        referencia.setFont(new java.awt.Font("MS Gothic", 2, 11)); // NOI18N
        referencia.setText("REFFEREBBCUA");
        jPanel1.add(referencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("OCR-B 10 BT", 3, 14)); // NOI18N
        jLabel5.setText("Pedido finalizado");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, 50));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("MS Gothic", 3, 11)); // NOI18N
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 80, 50));

        jLabel6.setFont(new java.awt.Font("MS Gothic", 3, 12)); // NOI18N
        jLabel6.setText("Endereço:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 64, -1, 40));

        jLabel7.setFont(new java.awt.Font("MS Gothic", 3, 11)); // NOI18N
        jLabel7.setText("Nº");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel8.setFont(new java.awt.Font("MS Gothic", 3, 10)); // NOI18N
        jLabel8.setText("P/  de referência");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel9.setFont(new java.awt.Font("MS Gothic", 3, 11)); // NOI18N
        jLabel9.setText("Pedidos:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 260));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telafim1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telafim1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telafim1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telafim1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telafim1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel casanum;
    private javax.swing.JLabel endereco;
    public javax.swing.JList<String> itemsfinal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblopa;
    private javax.swing.JLabel lblpagar;
    private javax.swing.JLabel lbltroco;
    private javax.swing.JLabel referencia;
    // End of variables declaration//GEN-END:variables

    void SetVisible(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
