/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package observa;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import modelo.ModeloJframe1;
/**
 *
 * @author positivo
 */
public class trocomerda extends javax.swing.JFrame {
    double total;
    Object[] lista;
    String endrc;
    String numerocasa;
    String naoaguentomais;
    boolean seraQUsou = false;
    /**
     * Creates new form trocomerda
     */
    public trocomerda() {
        initComponents();
    }
    
    public void exportarPreco(double tudoo, Object[] listaa, String endereco, String ncasa, String ptrefe, boolean usouCartao){
        total = tudoo;
        lista = listaa;
        endrc = endereco;
        numerocasa = ncasa;
        naoaguentomais = ptrefe;
        seraQUsou = usouCartao;
        if (seraQUsou == true) {
            this.dispose();
            concluido conc = new concluido();
            int trooco = 0;
            conc.exportarPreco(trooco, total, lista, endrc);
            conc.setVisible(true);            
        }
    }
    
    public void usouEssaDesgrama() {
        this.dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(249, 233, 158));

        jButton1.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        jButton1.setText("sim");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        jButton2.setText("não");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        jLabel1.setText("Vai precisar de troco?");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image4/nikiforov.JPG"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addComponent(jLabel2)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.dispose();
        telafim1 fim = new telafim1();
        ModeloJframe1 model = new ModeloJframe1();
        
//
    String input;
        String string = "";
        do {
            input = JOptionPane.showInputDialog("Troco pra quanto?");
            if (input.matches("^[0-9]*$")) {
                string = input;
            }
            else {
                JOptionPane.showMessageDialog(null, "Somente números!!");                
            }
        } while (!input.matches("^[0-9]*$"));
//
//         String troco = JOptionPane.showInputDialog("Troco pra quanto?");
/*         while (troco.equals("")){
             JOptionPane.showMessageDialog(null, "Campo não pode permanecer vazio.");
                 troco = JOptionPane.showInputDialog( "Troco pra quanto?");
       
         }
*/
    int trooco = Integer.parseInt(string);
    if (trooco <= total) {
        JOptionPane.showMessageDialog(null, "Então você não precisa de troco.");
        fim.exportarTroco(trooco, total, lista, endrc, numerocasa, naoaguentomais);
        fim.setVisible(true);
    } else {
        model.setTroco(trooco);
//            fim.exportarPreco(total);
            fim.exportarTroco(trooco, total, lista, endrc, numerocasa, naoaguentomais);
            fim.setVisible(true);
    }
       //FINALMENTEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE CACETA 
       //ainda nn grrrrr
       //agrssssssss
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
      this.dispose();
        telafim1 fim = new telafim1();
        ModeloJframe1 model = new ModeloJframe1();
         String troco = JOptionPane.showInputDialog("Troco pra quanto?");
         while (troco.equals("")){
             JOptionPane.showMessageDialog(null, "Campo não pode permanecer vazio.");
                 troco = JOptionPane.showInputDialog( "Troco pra quanto?");
       
         }
    int trooco = Integer.parseInt(troco);
    if (trooco <= total) {
        JOptionPane.showMessageDialog(null, "Então você não precisa de troco.");
        fim.exportarTroco(trooco, total, lista, endrc, numerocasa, naoaguentomais);
        fim.setVisible(true);
    } else {
        model.setTroco(trooco);
//            fim.exportarPreco(total);
            fim.exportarTroco(trooco, total, lista, endrc, numerocasa, naoaguentomais);
            fim.setVisible(true);
    }
       //FINALMENTEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE CACETA 
       //ainda nn grrrrr
       //agrssssssss
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//fazer se ele n quiser troco
//a gnt usou tanto "querer troco q eu esqueci disso
        this.dispose();
        telafim1 fim = new telafim1();
        int trooco = 0;
        fim.exportarTroco(trooco, total, lista, endrc, numerocasa, naoaguentomais);
        fim.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
     this.dispose();
        telafim1 fim = new telafim1();
        int trooco = 0;
        fim.exportarTroco(trooco, total, lista, endrc, numerocasa, naoaguentomais);
        fim.setVisible(true);
    }//GEN-LAST:event_jButton2KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(trocomerda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(trocomerda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(trocomerda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(trocomerda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new trocomerda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
